vim.o.ru=true
vim.o.hlsearch=true
vim.o.incsearch = true
vim.o.cursorline=true
vim.o.showmode=true
vim.o.autoindent=true
vim.o.smartindent = true
vim.o.expandtab=true
vim.o.splitbelow=true
vim.o.breakindent = true
vim.o.showmatch=true
vim.o.tabstop =4
vim.o.shiftwidth =4
vim.o.fileencodings='utf-8'
vim.o.whichwrap = "<,>,[,]"
vim.wo.number = true
vim.wo.relativenumber = true
vim.o.completeopt = "noinsert,menuone,noselect"
vim.g.loaded_netrw = 1
vim.g.loaded_netrwPlugin = 1
vim.g.encoding = "UTF-8"
--vim.o.updatetime = 100
vim.opt.termguicolors = true
vim.g.python3_host_prog='/data/data/com.termux/files/usr/bin/python3.10'
vim.g.python_execute='/data/data/com.termux/files/usr/bin/python3.10'
--vim.g.did_load_filetypes = 1
vim.g.do_filetype_lua = 1
vim.g.loaded_perl_provider=0
vim.g.loaded_ruby_provider=0
